apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-backend" (include "furniture.fullname" .) }}
  namespace: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: {{ .Values.backend.containerPort }}
    targetPort: {{ .Values.backend.containerPort }}
    protocol: TCP