apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-frontend" (include "furniture.fullname" .) }}
  namespace: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - port: {{ .Values.frontend.containerPort }}
    targetPort: {{ .Values.frontend.containerPort }}
    protocol: TCP